version: '3'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: peepatnice1212
      MYSQL_DATABASE: nicedb
    ports:
      - "3310:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  spring-boot:
    build: ./back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: peepatnice1212
    depends_on:
      - mysql
  nextjs:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot